# Generated by Django 4.0.5 on 2023-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
