# Generated by Django 4.0.5 on 2023-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_checkoutproducts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='date',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
