# Generated by Django 4.0.5 on 2023-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_checkoutproducts_date_alter_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
