# Generated by Django 4.0.5 on 2023-01-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_checkout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField(blank=True, default=0, null=True)),
                ('mode', models.CharField(blank=True, default='COD', max_length=20, null=True)),
                ('paymentmode', models.CharField(blank=True, default='COD', max_length=20, null=True)),
                ('orderstatus', models.CharField(blank=True, default='COD', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rppid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpoid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpsid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutProducts1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('q', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.checkout1')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='checkout',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='CheckoutProducts',
        ),
    ]
