# Generated by Django 4.0.5 on 2023-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_checkout_checkoutproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paymentstatus',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='orderstatus',
            field=models.CharField(blank=True, default='Not Packed', max_length=20, null=True),
        ),
    ]
