# Generated by Django 4.0.5 on 2023-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_checkout_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='product_id',
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='productid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
