# Generated by Django 4.0.5 on 2023-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_checkout_orderstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='active',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.AddField(
            model_name='checkout',
            name='orderstatus',
            field=models.CharField(blank=True, default='Not Packed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='paymentmode',
            field=models.CharField(blank=True, default='COD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paymentstatus',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
