# Generated by Django 4.0.5 on 2023-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_checkout_active_remove_checkout_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='orderstatus',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='paymentstatus',
        ),
        migrations.AddField(
            model_name='checkout',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Packed'), (3, 'Out for Delivery'), (4, 'Delivered')], default=1),
        ),
    ]
